### 테스트
GET localhost:8080/test?token=eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJ1c2VyMUBleGFtcGxlLmNvbSIsImVtYWlsIjoidXNlcjFAZXhhbXBsZS5jb20ifQ.a_tH1qUTHosKPlBe9NTIoxasue7PNJ3NKTjFLBQYclM8C0iHlkwEMwWP-ckIYhdx
Content-Type: application/json
Authorization: